### ISSUE TITLE
Add ability to use "response"

### ISSUE THREAD

**Issue by matiboy** [serverless/serverless-websockets-plugin#12]
Two-way communication is possible so long as the route has an Integration Response

Since implementation is LAMBDA_PROXY, the integration response does nothing but pass on the response to the socket (its body becomes the socket's body)
![image](https://user-images.githubusercontent.com/487758/50568951-d5d05800-0d95-11e9-96ec-27cc18574505.png)

Could this be a feature of this plugin, to add a "twoWay: true" option on the routes?

**Comment by zhammer** [comment]
This'd be really nice. All that's needed on the console is clicking 'add integration response'. Not sure if there's cloudformation code for enabling.

Docs: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-responses.html

**Comment by lolcoolkat** [comment]
Can someone please explain what this "two way communication" allows me to do? And could we possibly get an example of this in the `/example` directory of this plugin :D Thanks!

**Comment by braindx** [comment]
By default, if the client issues a request to the API Gateway, the return value of the lambda function that is run is not passed back to the client. The integration response enables that.

**Comment by lolcoolkat** [comment]
@braindx So when I send `{"action": "twoway", "data": "example"}` for example I should see whatever I specified to return in the client right? In my case I have it returning `{ statusCode: 200 }`. However when I use wscat and send that payload.. it doesn't return anything. What am I doing wrong :D

**Comment by braindx** [comment]
Are you using the version from GitHub or are you just using npm to install the plugin? I don't believe a new version has been published to npm yet.

**Comment by lolcoolkat** [comment]
I'm loading the plugin via an `index.js`, so I do have the new code that was added recently :)

**Comment by braindx** [comment]
Oh, ok, In that case, I would first login to the AWS console website, go to API Gateway, and inspect the route that you've marked with "routeResponseSelectionExpression: $default" in your serverless.yml. Ensure that it looks like the screenshot in the first post of this issue and has the integration response enabled rather than just the top outgoing row.

**Comment by lolcoolkat** [comment]
@braindx Yep it looks exactly like you have it in the image in the first post!

**Comment by braindx** [comment]
Then that should be all you need to do! Just return a body from the Lambda function like you would for a normal HTTP API gateway: `{ statusCode: 200, body: 'Test!' }`

**Comment by lolcoolkat** [comment]
@braindx According to this https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-response.html I should be able to click on the `Route Response` box and edit the Response Modeling info.. but the box is just greyd out like in picture above. Any ideas? Maybe that could be the reason :P

**Comment by braindx** [comment]
I believe that's greyed out because it's using the LAMBDA_PROXY, which is normal. I've never used that tab in Chrome, so I couldn't say what you should see where. I certainly see the response when using wscat [as described in the AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-wscat.html). Again, make sure that you're returning a body and you may want to check your CloudWatch logs for any potential errors.

**Comment by lolcoolkat** [comment]
I don't see any errors in CloudWatch.. and this is the body i'm returning from the `sendMessage` function in lambda. 

``{ statusCode: 200, body: '{"data":"test"}' }``

Here is my function.. I'm returning the success object at the end..
![img](https://i.imgur.com/OJWCEeK.png)

**Comment by lolcoolkat** [comment]
@braindx Seems to be working now! Not really sure why it wasn't before haha :D Thanks for the help tho!

**Comment by lolcoolkat** [comment]
@braindx Are route responses allowed on the $connect route? I added a route response to it.. via the AWS CLI.. and then tried to deploy my API.. and I get a ` Internal server error`.

![img](https://i.imgur.com/qHcvuVy.png)

**Comment by braindx** [comment]
I don’t believe you’re able to add one to the $connect route via the AWS Console so I would guess no.

**Comment by lolcoolkat** [comment]
Ah ok.. I see a button on the connect route so I figured i'd ask thanks!

![img](https://i.imgur.com/xM35mBZ.png)

**Comment by braindx** [comment]
Oh, I don’t know. Give it a shot via the console and see if it works that way.

**Comment by eahefnawy** [comment]
What is an example use case for integration response?

Based on my experience, web sockets are usually async and when you send some data to the lambda, you don't really expect anything back. Same goes when the server sends data to the client

**Comment by braindx** [comment]
You would want this anytime you intend to use the websocket-based API gateway more like a traditional HTTP gateway.

Imagine in the chat example that you want to add an extra route to fetch a user’s profile. The client would potentially issue that request when they clicked on a user’s name in the chat window and would want a response.

**Comment by zhammer** [comment]
some protocols built on websockets also involve initial / closing 'handshakes' between client and server, in which integrated responses would be helpful.

checkout the message flow for establishing a connection for a graphql subscription in the apollo protocol
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#messages-flow

**Comment by zhammer** [comment]
^ basically after establishing the websocket connection, the client sends the graphql subscription string, and the server will respond with a success or failure based on whether that subscription string is valid. (afterwards, the server asynchronously sends the client messages as new data events occur.)

honestly not sure if using integrated responses for the handshake is _better_ overall, but it seems like a use case.

**Comment by eahefnawy** [comment]
@braindx @zhammer thank you both! 😊 ... so in that case you think an option to turn on response would make sense?

**Comment by braindx** [comment]
Not sure what you’re asking. I resolved this issue in PR #18 with what I estimated will be closest to the CloudFormation API that is ultimately released.

**Comment by eahefnawy** [comment]
@braindx oh sorry, didn't realize Jared merged that in! This should be closed then!

Thanks again @braindx
