### ISSUE TITLE
Issue with the example sls project: 502 error

### ISSUE THREAD

**Issue by mcat-ee** [serverless/serverless-websockets-plugin#13]
Hey!

I installed the example code in a fresh environment, however I'm getting an error while attempting to connect with the following command:
`wscat -c wss://*******884.execute-api.us-east-1.amazonaws.com/dev`

I receive the following error in response: 
`error: Unexpected server response: 502`

Upon attempting to check the logs for the connectionManager I received the following error:
```
$ sls logs -f connectionManager
 
  Serverless Error ---------------------------------------
 
  1 validation error detected: Value '[]' at 'logStreamNames' failed to satisfy constraint: Member must have length greater than or equal to 1
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.5.0
     Serverless Version:     1.35.1
```

Am I doing something wrong or is this indicative of a bug?

**Comment by zloof** [comment]
I get the same error, I check at cloudwatch  and I can see "SyntaxError: await is only valid in async function"

**Comment by Skithy** [comment]
Managed to fix the syntax error.
Inside websocket-client send function, the ```.catch(err =>``` is missing an async, which was breaking ```await db.fetchConnectionSubscriptions```
```js
await this.client
      .postToConnection({
        ConnectionId,
        Data: JSON.stringify(payload),
      })
      .promise()
      .catch(async err => {
        console.log(JSON.stringify(err))

        if (err.statusCode === 410) {
          // unsub all channels connection was in
          const subscriptions = await db.fetchConnectionSubscriptions(
            ConnectionId
          )
...
```

**Comment by shortjared** [comment]
@Skithy want to submit a PR? Great catch!
