### ISSUE TITLE
Add minimum supported serverless version in readme

### ISSUE THREAD

**Issue by zhammer** [serverless/serverless-websockets-plugin#14]
Went through a lot of trouble debugging an issue (same as in #10) that prevented me from deploying / removing stack formations with this plugin. Updating serverless to 1.35 fixed the problem.

It'd be great to have the minimum required serverless version on the readme! Even better, if that could be included in the error message.

**Comment by eahefnawy** [comment]
thanks @zhammer ... you're right. I just opened #15 for this 🙌
