### ISSUE TITLE
Can't update the route expression

### ISSUE THREAD

**Issue by zhammer** [serverless/serverless-websockets-plugin#17]
Anyone else having trouble changing the route expression path? Even when i try to change manually in the console, and the gui shows the updated route expression, routes are still based on request.body.action

**Comment by zhammer** [comment]
So outside of this bugginess within the aws console, it seems that this plugin only sets the route selection expression the first time the service is deployed:

https://github.com/serverless/serverless-websockets-plugin/blob/e234d09ec1af256ead5ee74552c1ac9747cd24f6/src/index.js#L104-L117

**Comment by eahefnawy** [comment]
@zhammer Thanks for that! that's a good point! we should use `updateApi` for this. A PR is more than welcome as I won't be able to get that fix in soon 😊

**Comment by zhammer** [comment]
ha well i'll be playing around with this plugin a good amount in the next few weeks so maybe i'll put up a few PRs if I find issues!

**Comment by eahefnawy** [comment]
thanks @zhammer ... really appreciated 😊
