### ISSUE TITLE
CloudFormation support for config

### ISSUE THREAD

**Issue by waynerobinson** [serverless/serverless-websockets-plugin#32]
It looks like AWS have finally added CloudFormation support for WebSockets. 🍾🎉

https://aws.amazon.com/about-aws/whats-new/2019/02/automate-websocket-api-creation-in-api-gateway-with-cloudformation/

**Comment by eahefnawy** [comment]
Thanks @waynerobinson ... yep, we're working on it in core!

**Comment by viktorlarsson** [comment]
So, is this plugin going to be needed?
