### ISSUE TITLE
Custom authorizer support?

### ISSUE THREAD

**Issue by waynerobinson** [serverless/serverless-websockets-plugin#4]
Awesome work on this plugin. :)

Just wondering though whether this plugin supports custom authorizers for WS?

**Comment by waynerobinson** [comment]
Might have a go, depends on how complex the API is I guess. Haven’t really worked with API Gateway directly — Serverless does an excellent job at abstracting away all its complexity. 😀

**Comment by lolcoolkat** [comment]
I'm thinking about combining AWS Appsync with API Gateway Websockets :D Haven't really thought too much of it through though.. but I believe I can authorize the user via Appsync Authorization and do everything I want with Websockets through API Gateway!

**Comment by waynerobinson** [comment]
If you’re already using AppSync and GraphQL, Subscriptions are probably a better option if you want to use pushed data.

**Comment by viktorlarsson** [comment]
I would like to upvote this. Alot. : )

**Comment by tomasdev** [comment]
Braindx has put a PR in place, how do we feel about merging?

**Comment by eahefnawy** [comment]
Merged! 🙌

**Comment by psoares-resilient** [comment]
Hello, awesome work! 
do you have a planned release schedule to make this available through npm?

Thanks!

**Comment by ryanhelms** [comment]
+1
