### ISSUE TITLE
Connections should be removed from table for inactive connections (status code 401)

### ISSUE THREAD

**Issue by lolcoolkat** [serverless/serverless-websockets-plugin#5]
**This issue report is for the `example` directory in this repo.**

Check the example below posted by the AWS team as their example for sending messages. If the connection is no longer open with the client, when running `postToConnection`, the connection should be removed from the table :)

Check: https://github.com/aws-samples/simple-websockets-chat-app/blob/master/sendmessage/app.js#L30-L39

**Comment by lolcoolkat** [comment]
@shortjared For sure @shortjared :) The only reason I recommended adding it to this example is because i've noticed multiple times when closing my terminal window that the connection in the DynamoDB table stays :P I'm sure this is one of the "rare" situations you are referencing (I'm sure in the browser its different). But it would be nice to handle this edge case anywho :D

**Comment by shortjared** [comment]
Hmm. Yeah. Super easy fix. I will do it tomorrow. https://github.com/serverless/serverless-websockets-plugin/blob/e3050cb987306d6adfdbbba206a06ef577155975/example/src/websocket-client.js#L63-L68

Just need to query for all the connection records here and then delete 'em.

**Comment by shortjared** [comment]
Fixed by #19
